config/routes.rb
# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                                  root GET    /                                                                                        products#index
#                                search GET    /search(.:format)                                                                        products#search
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  root 'products#index'

  get 'search', to: 'products#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    after_commit do
      __elasticsearch__.index_document
    end

    after_commit on: [:destroy] do
      __elasticsearch__.delete_document
    end

    def as_indexed_json(_options = {})
      as_json(only: %i[title tags description price country])
    end

    settings index: { number_of_shards: 1 } do
      mapping dynamic: false do
        indexes :title, type: :text, analyzer: :autocomplete
        indexes :tags, type: :text, analyzer: :english
        indexes :description, type: :text, analyzer: :english
        indexes :country, type: :text
        indexes :price, type: :float
      end
    end

    def self.search(query, filters)
      set_filters = lambda do |context_type, filter|
        @search_definition[:query][:bool][context_type] |= [filter]
      end

      @search_definition = {
        size: 25, query: { bool: { must: [], should: [], filter: [] } }
      }

      if query.blank? && filters[:price].andand[:lte].blank? &&
         filters[:price].andand[:gte].blank? &&
         filters[:country].blank?
        set_filters.call(:must, match_all: {})
      end

      if query.present?
        set_filters.call(:should, match: { title: { query: query, boost: 3 } })
        set_filters.call(:should, match: { tags: { query: query, boost: 2 } })
        set_filters.call(
          :should,
          match: { description: { query: query, boost: 1 } }
        )
      end

      if filters[:price].andand[:lte].present? ||
         filters[:price].andand[:gte].present?
        gte = filters[:price][:gte].to_f unless filters[:price][:gte].blank?
        lte = filters[:price][:lte].to_f unless filters[:price][:lte].blank?

        set_filters.call(:filter, range: { price: { gte: gte, lte: lte } })
      end

      if filters[:country].present?
        set_filters.call(:filter, match: { country: filters[:country] })
      end
      
      __elasticsearch__.search(@search_definition)
    end
  end

  class_methods do
    def settings_attributes
      {
        index: {
          analysis: {
            analyzer: {
              autocomplete: {
                type: :custom,
                tokenizer: :standard,
                filter: %i[lowercase autocomplete]
              }
            },
            filter: {
              autocomplete: { type: :edge_ngram, min_gram: 2, max_gram: 25 }
            }
          }
        }
      }
    end
  end
end

app/models/product.rb
require 'elasticsearch/model'

class Product < ApplicationRecord
  include Searchable

  paginates_per 25
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.order(:title).page product_params[:page]
    @countries = Product.all.pluck(:country).uniq.sort
  end

  def search
    search = product_params[:search]

    @products = []
    unless search.blank? && params[:price].blank? && params[:country].blank?
      @products = Product.search(search, params).page(params[:page]).records
    end
  end

  private

    # Only allow a list of trusted parameters through.
    def product_params
      params.permit(:page, :search, :country, :price => {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spocket Search</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tags %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_paginate.html.erb
<%= paginate products, remote: true  %>

app/views/products/_products.html.erb
<% products.each_with_index do |product, index| %>
  <tr>
    <td><%= index + 1 %></td>
    <td><%= product.title %></td>
    <td><%= product.description %></td>
    <td><%= product.tags %></td>
    <td><%= product.country %></td>
    <td>$<%= product.price %></td>
  </tr>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <h1 class="center">Spocket Product Search Engine</h1>

  <%= form_with url: search_path, method: "GET", class: 'form-group', local:
  false do |f| %> <%= f.text_field :search, class: 'form-control', placeholder:
  'Search'%> <%= f.submit "Search", class: "btn btn-primary" %> <% end %>

  <div class="row">
    <div class="col-md-2">
      <%= form_with url: search_path, method: "GET", class: 'form-group', local:
      false do |f| %>

      <div class="row">
        <div class="form-group col-lg-12">
          <%= f.label :country, 'Country' %> <%= f.select(:country, @countries,
          { prompt: 'Select Country' }, { class: 'form-control', id: 'country'
          }) %>
        </div>
        <%= f.fields_for :price do |price_fields| %>
        <div class="form-group col-lg-12">
          <%= price_fields.label :gte, 'Lowest Price' %> <%=
          price_fields.text_field :gte, placeholder: 'Lowest Price e.g 500' %>
        </div>
        <div class="form-group col-lg-12">
          <%= price_fields.label :lte, 'Highest Price' %> <%=
          price_fields.text_field :lte, placeholder: 'Highest Price e.g 1500' %>
        </div>
        <% end %>
      </div>

      <%= f.submit "Apply Filters", class: "btn btn-primary" %> <% end %>
    </div>
    <div class="col-md-10">
      <table>
        <thead>
          <tr>
            <th>Number</th>
            <th>Title</th>
            <th>Description</th>
            <th>Tags</th>
            <th>Country</th>
            <th>Price</th>
          </tr>
        </thead>

        <tbody id="products">
          <%= render 'products/products', products: @products %>
        </tbody>
      </table>

      <br />

      <div id="paginate">
        <%= render 'products/paginate', products: @products %>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/search.js.erb
document.getElementById("products").innerHTML = "<%= escape_javascript render(partial: 'products/products', locals: { products: @products }) %>";
document.getElementById("paginate").innerHTML = "<%= escape_javascript render(partial: 'products/paginate', locals: { products: @products }) %>";

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @product.tags %>
</p>

<p>
  <strong>Country:</strong>
  <%= @product.country %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>